"use client";

import { useMemo, useState } from "react";

async function getJSON<T>(url: string): Promise<T> {
  const res = await fetch(url, { cache: "no-store" });
  return res.json();
}
async function postJSON<T>(url: string, body: any): Promise<T> {
  const res = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
  return res.json();
}

export default function EconomicsLoopClient() {
  const [days, setDays] = useState(7);
  const [usd, setUsd] = useState(100);
  const [out, setOut] = useState<any>(null);
  const [err, setErr] = useState<string | null>(null);

  const can = useMemo(() => days >= 1 && usd >= 1, [days, usd]);

  async function run() {
    setErr(null);
    setOut(null);
    try {
      const revenue = await getJSON<any>(`/api/agent/revenue?action=report&days=${days}`);
      const allocation = await postJSON<any>("/api/agent/allocate", { action: "plan", usd });
      const retireIntent = {
        kind: "retire.intent.v1",
        usd,
        note: "Intent only. Use /retire flow for execution.",
        requiresApproval: true,
      };
      const proof = {
        kind: "netnet.proof.v1",
        subject: { type: "economics.loop", windowDays: days },
        refs: {},
        claims: { revenue, allocation, retireIntent },
        createdAt: new Date().toISOString(),
      };
      setOut({ ok: true, revenue, allocation, retireIntent, proof });
    } catch (e: any) {
      setErr(e?.message || "loop_failed");
    }
  }

  async function createWork() {
    if (!out?.ok) return;
    setErr(null);
    try {
      const title = `Economics loop (${days}d): $${usd} allocation`;
      const res = await postJSON<any>("/api/work", {
        title,
        description: "Generated by Economics Loop (proposal-only). Attach proof/packet outputs and approve next steps.",
        tags: ["economics", "allocation", "retire-intent"],
        priority: "HIGH",
      });
      setOut({ ...out, work: res });
    } catch (e: any) {
      setErr(e?.message || "work_failed");
    }
  }

  return (
    <div className="grid gap-3 rounded-2xl border border-white/10 bg-white/5 p-4">
      <div className="grid gap-2 sm:grid-cols-3">
        <label className="grid gap-1 text-sm">
          <span className="opacity-70">Revenue window (days)</span>
          <input
            type="number"
            className="rounded-xl border border-white/10 bg-black/20 px-3 py-2"
            value={days}
            min={1}
            max={90}
            onChange={(e) => setDays(Number(e.target.value))}
          />
        </label>
        <label className="grid gap-1 text-sm">
          <span className="opacity-70">Plan amount (USD)</span>
          <input
            type="number"
            className="rounded-xl border border-white/10 bg-black/20 px-3 py-2"
            value={usd}
            min={1}
            max={1_000_000}
            onChange={(e) => setUsd(Number(e.target.value))}
          />
        </label>
        <div className="flex items-end gap-2">
          <button
            className="w-full rounded-xl bg-white px-4 py-2 text-sm font-medium text-black disabled:opacity-40"
            onClick={run}
            disabled={!can}
          >
            Run loop
          </button>
        </div>
      </div>

      <div className="flex flex-wrap gap-2">
        <button
          className="rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-sm hover:bg-white/15 disabled:opacity-40"
          onClick={createWork}
          disabled={!out?.ok}
        >
          Create work item
        </button>
      </div>

      {err ? <div className="text-sm text-red-300">{err}</div> : null}
      {out ? (
        <pre className="max-h-[420px] overflow-auto rounded-xl border border-white/10 bg-black/30 p-3 text-xs">
          {JSON.stringify(out, null, 2)}
        </pre>
      ) : (
        <div className="text-xs opacity-60">Outputs include revenue report, allocation packet, retire intent, and proof.</div>
      )}
    </div>
  );
}
